stages:
  - build
  - build_and_release

variables:
  IMAGE_RELEASE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_RELEASE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  IMAGE_RELEASE_TAG_DEV: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-dev

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN $REGISTRY_URL

build_and_release:
  # This is an older version, because the current one still has some issues.
  # @see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/65511
  image: docker:19.03.0
  stage: build_and_release
  services:
    - docker:19.03.0-dind
  only:
    - tags
  script:
    # Test and release images
    - docker build -t $IMAGE_RELEASE_TAG .
    - docker push $IMAGE_RELEASE_TAG
    # Update latest
    - docker build -t $IMAGE_RELEASE_TAG_LATEST .
    - docker push $IMAGE_RELEASE_TAG_LATEST
    # Dev images
    - docker build -t $IMAGE_RELEASE_TAG_DEV -f ./with-xdebug/Dockerfile ./with-xdebug
    - docker push $IMAGE_RELEASE_TAG_DEV
