name: Build images for registry

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Building and pushing docker images to the GitHub Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push image for release
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/alpine-nginx-php8
          tag_with_ref: true

      - name: Build and push image for latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/alpine-nginx-php8
          tags: alpine-nginx-php8:latest

      - name: Build and push image for release containing dev tools
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          context: ./with-xdebug
          file: ./with-xdebug/Dockerfile
          repository: ${{ github.repository }}/alpine-nginx-php8
          tags: alpine-nginx-php8:${{ github.ref }}-dev
