name: Build and push images for registry

on:
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TAG: ${GITHUB_REF#refs/*/}

jobs:

  build:
    name: Building and pushing docker images to the GitHub Registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and Push - release
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/made/alpine-nginx-php8:${{ steps.get_tag_name.outputs.VERSION }}
            ${{ secrets.REGISTRY_URL }}/made/alpine-nginx-php8:latest
      -
        name: Build and Push - dev release
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: ./with-xdebug
          file: ./with-xdebug/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/made/alpine-nginx-php8:${{ steps.get_tag_name.outputs.VERSION }}-dev

